Repository blhutchings/CS-4820-Telling-Stories, pull requests merged in 2023-03, with the labels that each got.

#23 Aditya views
  package-lock.json
  package.json
  public/css/main.css
  public/menu-toggle-transition.js
  src/server.js
  temp.txt
  views/content-create.ejs
  views/forgotPassword.ejs
  views/homepage.ejs
  views/index.ejs
  views/login.ejs
  views/partial/_navHeaderUserHub.ejs
  views/registration.ejs
  views/resetPassword.ejs
  views/users.ejs
  wikiTemp.md
Labels: front-end

#21 majorly refactored server.js, split routes into diff files
  cypress.config.js
  cypress/e2e/1-getting-started/todo.cy.js
  cypress/e2e/2-advanced-examples/actions.cy.js
  cypress/e2e/2-advanced-examples/aliasing.cy.js
  cypress/e2e/2-advanced-examples/assertions.cy.js
  cypress/e2e/2-advanced-examples/connectors.cy.js
  cypress/e2e/2-advanced-examples/cookies.cy.js
  cypress/e2e/2-advanced-examples/cypress_api.cy.js
  cypress/e2e/2-advanced-examples/files.cy.js
  cypress/e2e/2-advanced-examples/location.cy.js
  cypress/e2e/2-advanced-examples/misc.cy.js
  cypress/e2e/2-advanced-examples/navigation.cy.js
  cypress/e2e/2-advanced-examples/network_requests.cy.js
  cypress/e2e/2-advanced-examples/querying.cy.js
  cypress/e2e/2-advanced-examples/spies_stubs_clocks.cy.js
  cypress/e2e/2-advanced-examples/storage.cy.js
  cypress/e2e/2-advanced-examples/traversal.cy.js
  cypress/e2e/2-advanced-examples/utilities.cy.js
  cypress/e2e/2-advanced-examples/viewport.cy.js
  cypress/e2e/2-advanced-examples/waiting.cy.js
  cypress/e2e/2-advanced-examples/window.cy.js
  cypress/e2e/firstTest.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
  src/account.js
  src/authenticate.js
  src/password.js
  src/registration.js
  src/server.js
  src/users.js
  tests/server.test.js
  tests/temp.test.js
  views/create.ejs
  views/forgotPassword.ejs
  views/index.ejs
  views/login.ejs
  views/partial/_header.ejs
  views/partial/_navHeader.ejs
  views/partial/_sitemap.ejs
  views/registration.ejs
  views/tempReg.ejs
Labels: bug, testing/continuous integration, front-end, back-end

#25 need this pushed to dev
  src/server.js
  views/registration.ejs
Labels: version update
